apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-server.fullname" . }}
  labels:
    {{- include "test-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "test-server.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "test-server.fullname" . }}
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - host: test.local.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "test-server.fullname" . }}
                port:
                  number: 80