name: Ansible Deploy
on:
  push:
    branches: [ main ]
jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Ansible
        run: "apt update && apt install -y ansible"

      - name: Verify
        run: |
          ansible --version
          ansible-playbook --version

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v5
        with:
          playbook: ci.yaml
          directory: ${{ gitea.workspace }}/ansible/playbooks
          key: ${{secrets.DELL_DOCKER_1_SSH_KEY}}
          options: |
            --inventory ansible/inventory.yaml
            --verbose
