name: Ansible Deploy
on:
  push:
    branches: [ main ]
jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    container:
      image: alpine/ansible:latest
    steps:
      - name: Install dependencies
        run: apk add git

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify
        run: |
          ansible --version
          ansible-playbook --version

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DELL_DOCKER_1_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy
        env:
          ANSIBLE_CONFIG: ${{ gitea.workspace }}/ansible/ansible.cfg
        run: make ci