version: "2.4"
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 784:784/udp
      # - 853:853/tcp
      - 9204:3000/tcp
      - 9203:80/tcp
      # - 443:443/tcp
    volumes:
      - ${DOCKER_DIR:-./}work:/opt/adguardhome/work
      - ${DOCKER_DIR:-./}config:/opt/adguardhome/conf
    restart: unless-stopped