---
secrets:
  JWT_SECRET:
    file: ${SYNO_DIR:-.}/authelia/secrets/JWT_SECRET
  SESSION_SECRET:
    file: ${SYNO_DIR:-.}/authelia/secrets/SESSION_SECRET
  STORAGE_ENCRYPTION_KEY:
    file: ${SYNO_DIR:-.}/authelia/secrets/STORAGE_ENCRYPTION_KEY
services:
  authelia:
    container_name: 'authelia'
    image: 'docker.io/authelia/authelia:latest'
    restart: 'unless-stopped'
    ports:
      - "9092:9091"
    secrets: ['JWT_SECRET', 'SESSION_SECRET', 'STORAGE_ENCRYPTION_KEY']
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/run/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/run/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/STORAGE_ENCRYPTION_KEY'
    volumes:
      - ${SYNO_DIR:-.}/authelia/config:/config
    dns:
      - 1.1.1.1
    network_mode: bridge