version: "2.4"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    networks:
      - proxy
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      # TODO: make the connection secure through traefik
      - N8N_SECURE_COOKIE=false
      #      - N8N_HOST=${DOMAIN_NAME}
      - N8N_PORT=5678
      #      - N8N_PROTOCOL=https
      - NODE_ENV=production
      #      - WEBHOOK_URL=${PUBLIC_DOMAIN_NAME}
      - GENERIC_TIMEZONE="Europe/Warsaw"
      - TZ="Europe/Warsaw"
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ${DOCKER_DIR:-.}/n8n:/home/node/.n8n
    labels:
      - docker-volume-backup.stop-during-backup=true
      - traefik.enable=true
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.routers.n8n.rule=Host(`${HOST}`)
      - traefik.http.routers.n8n.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.n8n.tls=true
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true