version: "2.4"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    ports:
      - "8083:5678"
    environment:
      #      - N8N_HOST=${DOMAIN_NAME}
      - N8N_PORT=5678
      #      - N8N_PROTOCOL=https
      - NODE_ENV=production
      #      - WEBHOOK_URL=${PUBLIC_DOMAIN_NAME}
      - GENERIC_TIMEZONE="Europe/Warsaw"
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=true
    volumes:
      - ${DOCKER_DIR:-.}/n8n:/home/node/.n8n
