version: '2.4'
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    hostname: changedetection
    volumes:
      - ${DOCKER_DIR:-./}/changedetection/datastore:/datastore
    ports:
      - "9092:5000"
    restart: unless-stopped
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true
    depends_on:
      playwright-chrome:
        condition: service_started
  playwright-chrome:
    hostname: playwright-chrome:latest
    image: browserless/chrome
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=150000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=300000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_STEALTH=true