version: '2.4'
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    user: "${UID:-1000}:${GID:-1000}"
    container_name: changedetection
    networks:
      - proxy
    volumes:
      - ${DOCKER_DIR:-./}/changedetection/datastore:/datastore
    restart: unless-stopped
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
    depends_on:
      - playwright-chrome
    labels:
      - traefik.enable=true
      - traefik.http.services.changedetection.loadbalancer.server.port=5000
      - traefik.http.routers.changedetection.rule=Host(`changedetection.local.psmarcin.dev`)
      - traefik.http.routers.changedetection.tls.certresolver=localresolver
      - traefik.http.routers.changedetection.tls=true
  # Used for fetching pages via Playwright+Chrome where you need Javascript support.
  # RECOMMENDED FOR FETCHING PAGES WITH CHROME
  playwright-chrome:
    container_name: playwright-chrome
    hostname: playwright-chrome
    image: dgtlmoon/sockpuppetbrowser:latest
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - SCREEN_WIDTH=1024
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=5

networks:
  proxy:
    name: proxy
    external: true