version: '2.4'
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    hostname: changedetection
    networks:
      - proxy
    volumes:
      - ${DOCKER_DIR:-./}/changedetection/datastore:/datastore
    restart: unless-stopped
    #    environment:
    #      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true
    depends_on:
      playwright-chrome:
        condition: service_started
    labels:
      - traefik.enable=true
      - traefik.http.services.changedetection.loadbalancer.server.port=5000
      - traefik.http.routers.changedetection.rule=Host(`changedetection.local.psmarcin.dev`)
      - traefik.http.routers.changedetection.tls.certresolver=localresolver
      - traefik.http.routers.changedetection.tls=true
  # Used for fetching pages via Playwright+Chrome where you need Javascript support.
  # RECOMMENDED FOR FETCHING PAGES WITH CHROME
  playwright-chrome:
    container_name: playwright-chrome
    hostname: playwright-chrome
    image: dgtlmoon/sockpuppetbrowser:latest
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=5
#  playwright-chrome1:
#    hostname: playwright-chrome
#    image: browserless/chrome:latest
#    restart: unless-stopped
#    environment:
#      - SCREEN_WIDTH=1920
#      - SCREEN_HEIGHT=1024
#      - SCREEN_DEPTH=16
#      - ENABLE_DEBUGGER=false
#      - PREBOOT_CHROME=true
#      - CONNECTION_TIMEOUT=150000
#      - MAX_CONCURRENT_SESSIONS=10
#      - CHROME_REFRESH_TIME=300000
#      - DEFAULT_BLOCK_ADS=true
#      - DEFAULT_STEALTH=true

networks:
  proxy:
    name: proxy
    external: true