version: "2.4"
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    restart: unless-stopped
    volumes:
      - ${DOCKER_DIR:-./}:/srv
      - filebrowser-database:/database/
      - filebrowser-config:/config/
    networks:
      - proxy
    ports:
      - "8084:80"
    labels:
      - docker-volume-backup.stop-during-backup=true
      - traefik.enable=true
      - traefik.http.services.filebrowser.loadbalancer.server.port=80
      - traefik.http.routers.filebrowser.rule=Host(`${HOST}`)
      - traefik.http.routers.filebrowser.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.filebrowser.tls=true
      - traefik.docker.network=proxy
    environment:
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
      - DNSMASQ_LISTENING=all

volumes:
  filebrowser-database:
  filebrowser-config:

networks:
  proxy:
    external: true