services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ${DOCKER_DIR:-.}/homer/assets:/www/assets
    ports:
      - "${HOMER_PORT:-9001}:8080"
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - INIT_ASSETS=0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"