services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ${DOCKER_DIR:-.}/homer/assets:/www/assets
    ports:
      - "${HOMER_PORT:-9001}:8080"
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - INIT_ASSETS=0
    restart: unless-stopped
    labels:
      - traefik.http.services.homer.loadbalancer.server.port=8080
      - traefik.http.routers.homer.rule=Host(`${HOST:-.}`)
      - traefik.http.routers.homer.tls.certresolver=localresolver
      - traefik.http.routers.homer.tls=true
      - traefik.docker.network=proxy
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"