version: "2.4"
services:
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    networks:
      - media
    # mem_limit: 256m
    # mem_reservation: 50m
    ports:
      - "9095:9117"
    volumes:
      - ${DOCKER_DIR:-./}/jackett/config:/config
      - ${DOCKER_DIR:-./}/jackett/downloads:/downloads
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    networks:
      - media
    # mem_limit: 256m
    # mem_reservation: 50m
    ports:
      - "9094:8989"
    volumes:
      - ${DOCKER_DIR:-./}/sonarr/config:/config
      - ${DOCKER_DIR:-./}/downloads:/downloads
      - ${DOCKER_DIR:-./}/downloads/tv:/tv
    depends_on:
      - jackett
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    networks:
      - media
    # mem_limit: 256m
    # mem_reservation: 50m
    ports:
      - "9096:7878"
    volumes:
      - ${DOCKER_DIR:-./}/radarr/config:/config
      - ${DOCKER_DIR:-./}/downloads:/downloads
      - ${DOCKER_DIR:-./}/downloads/movies:/movies
    depends_on:
      - jackett
    restart: unless-stopped

  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    networks:
      - media
    # mem_limit: 256m
    # mem_reservation: 64m
    ports:
      - "9098:5055"
    volumes:
      - ${DOCKER_DIR:-./}/overseerr/config:/app/config
    depends_on:
      - sonarr
      - radarr
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    networks:
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${DOCKER_DIR:-./}/bazarr/config:/config
      - ${DOCKER_DIR:-./}/downloads/movies:/movies
      - ${DOCKER_DIR:-./}/downloads/tv:/tv
    ports:
      - "9201:6767"
    restart: unless-stopped

networks:
  media:
    external:
      name: media