version: "2.4"
services:
  nocodb:
    image: nocodb/nocodb:latest
    networks:
      - utilites
    ports:
      - "9205:8080"
    restart: always
    environment:
      NC_DB: "pg://postgres:5432?u=postgres&p=password&d=nocodb"

volumes:
  utils_pgdata:
    external:
      name: utils_pgdata

networks:
  utilites:
    external:
      name: utilites