version: "2.4"
services:
  nocodb:
    image: nocodb/nocodb:latest
    networks:
      - utilites
    ports:
      - "9205:8080"
    restart: always
    environment:
      NC_DB: "pg://postgres:5432?u=ncdb_user&p=pass&d=ncdb"
    labels:
      - traefik.enable=true
      - traefik.http.services.ncdb.loadbalancer.server.port=8080
      - traefik.http.routers.ncdb.rule=Host(`${NCDB_DOMAIN:-}`)

volumes:
  utils_pgdata:
    external:
      name: utils_pgdata

networks:
  utilites:
    external:
      name: utilites