version: "2.4"
services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    networks:
      - utilites
      - proxy
    container_name: paperless
    restart: unless-stopped
    volumes:
      - ${DOCKER_DIR:-.}/paperless/data:/usr/src/paperless/data
      - ${DOCKER_DIR:-.}/paperless/media:/usr/src/paperless/media
      - ${FILES_DIR:-.}/export:/usr/src/paperless/export
      - ${FILES_DIR:-.}/consume:/usr/src/paperless/consume
    labels:
#      - docker-volume-backup.stop-during-backup=true
      - traefik.enable=true
      - traefik.http.services.paperless.loadbalancer.server.port=8000
      - traefik.http.routers.paperless.rule=Host(`paper.local.psmarcin.dev`)
      - traefik.http.routers.paperless.tls.certresolver=localresolver
      - traefik.http.routers.paperless.tls=true
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBNAME: postgres
      PAPERLESS_DBUSER: postgres
      PAPERLESS_DBPASS: postgres
      PAPERLESS_DBSSLMODE: disable
      PAPERLESS_OCR_LANGUAGES: pol
      PAPERLESS_TIME_ZONE: Europe/Warsaw
      PAPERLESS_SECRET_KEY: "Tse@n&L8eCHuZAsVmWH"
      PAPERLESS_ADMIN_USER: ${A_USER:-ps}
      PAPERLESS_ADMIN_PASSWORD: ${A_PASS:-ps123}
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"
      PAPERLESS_URL: ${A_URL:-http://localhost:9099}

networks:
  utilites:
    name: utilites
    external: true
  proxy:
    name: proxy
    external: true