version: "2.4"
services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    networks:
      - utilites
      - proxy
    container_name: paperless
    restart: unless-stopped
    # mem_limit: 1g
    # mem_reservation: 512m
#    ports:
#      - "9099:8000"
    volumes:
      - pl_data:/usr/src/paperless/data
      - pl_media:/usr/src/paperless/media
      - ${ROOT_DIR:-.}/export:/usr/src/paperless/export
      - ${ROOT_DIR:-.}/consume:/usr/src/paperless/consume
    labels:
      - docker-volume-backup.stop-during-backup=true
      - traefik.enable=true
      - traefik.http.services.paperless.loadbalancer.server.port=8000
      - traefik.http.routers.paperless.rule=Host(`paper.home.local`)
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBNAME: postgres
      PAPERLESS_DBUSER: postgres
      PAPERLESS_DBPASS: postgres
      PAPERLESS_DBSSLMODE: disable
      PAPERLESS_OCR_LANGUAGES: pol
      PAPERLESS_TIME_ZONE: Europe/Warsaw
      PAPERLESS_SECRET_KEY: "Tse@n&L8eCHuZAsVmWH"
      PAPERLESS_ADMIN_USER: ${A_USER:-ps}
      PAPERLESS_ADMIN_PASSWORD: ${A_PASS:-ps123}
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_URL: ${A_URL:-http://localhost:9099}

volumes:
  pl_data:
    name: paperless_pl_data
    external: true
  pl_media:
    name: paperless_pl_media
    external: true

networks:
  utilites:
    name: utilites
    external: true
  proxy:
    name: proxy
    external: true