version: "2.4"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.03.2
    network_mode: host
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '9203:80/tcp'
    restart: unless-stopped
    volumes:
      - ${DOCKER_DIR:-./}pihole:/etc/pihole
      - ${DOCKER_DIR:-./}pihole/dnsmasq.d:/etc/dnsmasq.d
    environment:
      - WEBPASSWORD=${WEBPASS:-pass}
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
      - DNSMASQ_LISTENING=all
    labels:
      - traefik.enable=true
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.http.routers.pihole.rule=Host(`pi.home.local`)
networks:
  proxy:
    name: proxy
    external: true