services:
  plex:
    image: lscr.io/linuxserver/plex:1.40.0.7998-c29d4c0c8
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=${PLEX_VERSION:-docker}
      - 'PLEX_CLAIM=${PLEX_CLAIM}'
    ports:
      - "32400:32400"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - plex_config:/config
      - plex_downloads_audiobooks:/volume1/docker/downloads/audiobooks
      - plex_downloads_audiobooks_complete:/volume1/docker/downloads/complete/audiobooks
      - plex_downloads_movies:/volume1/docker/downloads/movies
      - plex_downloads_movies_complete:/volume1/docker/downloads/complete/movies
      - plex_downloads_tv:/volume1/docker/downloads/tv
      - plex_downloads_tv_complete:/volume1/docker/downloads/complete/tv
      - ${DOCKER_DIR:-.}/plex/transcode:/transcode
    labels:
      - traefik.enable=true
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex.rule=Host(`${PLEX_DOMAIN:-}`)
    restart: unless-stopped

volumes:
  plex_config:
    driver_opts:
      type: cifs
      o: username=${SMB_USER:-.},password=${SMB_PASS:-.},uid=1000,gid=1000,vers=3.0,rw
      device: //${SMB_URI:-.}/plex
  plex_downloads_audiobooks:
    driver_opts:
      type: cifs
      o: username=${SMB_USER:-.},password=${SMB_PASS:-.},uid=1000,gid=1000,vers=3.0,rw
      device: //${SMB_URI:-.}/downloads/audiobooks
  plex_downloads_movies:
    driver_opts:
      type: cifs
      o: username=${SMB_USER:-.},password=${SMB_PASS:-.},uid=1000,gid=1000,vers=3.0,rw
      device: //${SMB_URI:-.}/downloads/movies
  plex_downloads_tv:
    driver_opts:
      type: cifs
      o: username=${SMB_USER:-.},password=${SMB_PASS:-.},uid=1000,gid=1000,vers=3.0,rw
      device: //${SMB_URI:-.}/downloads/tv
  plex_downloads_audiobooks_complete:
    driver_opts:
      type: cifs
      o: username=${SMB_USER:-.},password=${SMB_PASS:-.},uid=1000,gid=1000,vers=3.0,rw
      device: //${SMB_URI:-.}/downloads/complete/audiobooks
  plex_downloads_movies_complete:
    driver_opts:
      type: cifs
      o: username=${SMB_USER:-.},password=${SMB_PASS:-.},uid=1000,gid=1000,vers=3.0,rw
      device: //${SMB_URI:-.}/downloads/complete/movies
  plex_downloads_tv_complete:
    driver_opts:
      type: cifs
      o: username=${SMB_USER:-.},password=${SMB_PASS:-.},uid=1000,gid=1000,vers=3.0,rw
      device: //${SMB_URI:-.}/downloads/complete/tv