version: "2.4"
services:
  podsync:
    image: ghcr.io/mxpv/podsync
    network_mode: bridge
    ports:
      - "9204:8080"
    volumes:
      - podsync_data:/app/data/
      - podsync_config_toml:/app/config.toml
    dns: 1.1.1.1
    restart: unless-stopped

volumes:
  podsync_data:
    driver_opts:
      type: cifs
      o: username=${SMB_USER:-.},password=${SMB_PASS:-.},uid=1000,gid=1000,vers=1.0,rw
      device: //${SMB_URI:-.}/data
  podsync_config_toml:
    driver_opts:
      type: cifs
      o: username=${SMB_USER:-.},password=${SMB_PASS:-.},uid=1000,gid=1000,vers=1.0,rw
      device: //${SMB_URI:-.}/config.toml