version: "2.4"
services:
  podsync:
    image: mxpv/podsync:latest
    network_mode: bridge
    ports:
      - "9204:8080"
    volumes:
      - ${DOCKER_DIR:-./}/podsync/data:/app/data/
      - ${DOCKER_DIR:-./}/podsync/config.toml:/app/config.toml
    restart: unless-stopped