services:
  podsync:
    image: ghcr.io/mxpv/podsync
    network_mode: bridge
    ports:
      - "9204:8080"
    user: 1000:1000
    environment:
      PODSYNC_CONFIG_PATH: /config/config.toml
    volumes:
      - /opt/podsync/data:/app/data
      - /opt/podsync/data:/config
    restart: unless-stopped
