services:
  podsync:
    image: ghcr.io/mxpv/podsync
    container_name: podsync
    networks:
      - podsync_isolated
    ports:
      - "9204:8080"
    environment:
      PODSYNC_CONFIG_PATH: /config/config.toml
    dns:
      - 208.67.222.222
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - podsync_data:/app/data
      - ${SYNO_DIR:-.}/podsync/config:/config
    restart: unless-stopped
    entrypoint: "sleep 3600"

volumes:
  podsync_data:
    driver: local

networks:
  podsync_isolated:
    driver: bridge
    internal: false

