version: "2.4"
services:
  podsync:
    image: ghcr.io/mxpv/podsync
    network_mode: bridge
    ports:
      - "9204:8080"
    volumes:
      - ${DOCKER_DIR:-./}/podsync/data:/app/data/
      - ${DOCKER_DIR:-./}/podsync/config.toml:/app/config.toml
    dns: 1.1.1.1
    restart: unless-stopped
#    networks:
#      - proxy
#    labels:
#      - traefik.enable=true
#      - traefik.http.services.podsync.loadbalancer.server.port=8080
#      - traefik.http.routers.podsync.rule=Host(`podcasts.home.local`)
networks:
  proxy:
    name: proxy
    external: true