version: "2.4"
services:
  proxy:
    image: traefik:v2.11        # Review traefik documentation https://doc.traefik.io/traefik/
    container_name: traefik
#    network_mode: "host"
    mem_limit: 128m
    mem_reservation: 64m
    networks:
      - proxy
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:9091
      - --entrypoints.websecure.address=:9443
      - --api.disabledashboardad=true
      # - "--certificatesResolvers.le.acme.email=${EMAIL}"
      # - "--certificatesResolvers.le.acme.storage=acme.json"
      # - "--certificatesResolvers.le.acme.tlsChallenge=true"
      # - "--certificatesResolvers.le.acme.httpChallenge=true"
      # - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
      # - "--certificatesResolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "9091:9091"
      - "9443:9443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:2023.10.0
    container_name: cloudflared
    network_mode: "host"
    volumes:
      - ${DOCKER_DIR:-.}/cloudflared/config:/etc/cloudflared
    command: tunnel run
    restart: always

  uptime:
    container_name: uptime
    image: louislam/uptime-kuma:1-alpine
    networks:
      - proxy
    mem_limit: 256m
    mem_reservation: 128m
    labels:
      - traefik.enable=true
      - traefik.http.services.uptime.loadbalancer.server.port=3001
      - traefik.http.routers.uptime.rule=Host(`up.home.local`)
      - traefik.http.routers.uptime.tls=false
    volumes:
      - ${DOCKER_DIR:-.}/uptime/data:/app/data

  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.homer.loadbalancer.server.port=8080
      - traefik.http.routers.homer.rule=Host(`home.local`)
      - traefik.http.routers.homer.rule=Host(`s.home`)
      - traefik.http.routers.homer.rule=Host(`home.lan`)
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Europe/Warsaw
    volumes:
      - ${DOCKER_DIR:-.}/homer/assets:/www/assets

networks:
  proxy:
    name: proxy