version: "3.8"
services:
  #  TO Debug traefik, add whoami service
  whoami:
    image: traefik/whoami
    command:
      # It tells whoami to start listening on 2001 instead of 80
      - --port=2001
      - --name=iamfoo
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.whoami.loadbalancer.server.port=2001
      - traefik.http.routers.whoami.rule=Host(`${WHOAMI_HOST:-.}`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=localresolver
  proxy:
    image: traefik:v3        # Review traefik documentation https://doc.traefik.io/traefik/
    container_name: traefik
    #    network_mode: "host"
    networks:
      - proxy
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:9091
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:9443
      - --api.disabledashboardad=true
      - --certificatesresolvers.localresolver.acme.dnsChallenge=true
      - --certificatesresolvers.localresolver.acme.dnsChallenge.provider=cloudflare
      #      - --certificatesresolvers.localresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.localresolver.acme.email=${ACME_EMAIL:-.}
      - --certificatesresolvers.localresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.localresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --providers.file.directory=/dynamic
    ports:
      - "9091:9091"
      - "8443:9443"
      - "443:9443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/letsencrypt
      - ${DOCKER_DIR:-.}/traefik/dynamic:/dynamic:ro
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CF_TOKEN:-.}
      - CLOUDFLARE_ZONE_API_TOKEN=${CF_TOKEN:-.}
    restart: unless-stopped

networks:
  proxy:
    name: proxy

volumes:
  certs: