version: "2.4"
services:
  proxy:
    image: traefik:v3.1        # Review traefik documentation https://doc.traefik.io/traefik/
    container_name: traefik
    mem_limit: 128m
    mem_reservation: 64m
    networks:
      - proxy
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:9091
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:9443
      - --api.disabledashboardad=true
      - --certificatesresolvers.localresolver.acme.dnsChallenge=true
      - --certificatesresolvers.localresolver.acme.dnsChallenge.provider=cloudflare
#      - --certificatesresolvers.localresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.localresolver.acme.email=${ACME_EMAIL:-.}
      - --certificatesresolvers.localresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.localresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
    ports:
      - "9091:9091"
      - "9443:9443"
      - "443:9443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_DIR:-.}/traefik/letsencrypt:/letsencrypt
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CF_TOKEN:-.}
      - CLOUDFLARE_ZONE_API_TOKEN=${CF_TOKEN:-.}
    restart: unless-stopped

networks:
  proxy:
    name: proxy