version: "2.4"
services:
  proxy:
    image: traefik:v2.5.5        # Review traefik documentation https://doc.traefik.io/traefik/
    container_name: traefik
    network_mode: "host"
    mem_limit: 48m
    mem_reservation: 24m
    command:
      #      - "--log.level=DEBUG"
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:9091
      - --entrypoints.websecure.address=:9443
      # - "--certificatesResolvers.le.acme.email=${EMAIL}"
      # - "--certificatesResolvers.le.acme.storage=acme.json"
      # - "--certificatesResolvers.le.acme.tlsChallenge=true"
      # - "--certificatesResolvers.le.acme.httpChallenge=true"
      # - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
      # - "--certificatesResolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "9091:9091"
      - "9443:9443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  uptime:
    container_name: uptime
    image: louislam/uptime-kuma:1.11.1
    mem_limit: 128m
    mem_reservation: 64m
    labels:
      - traefik.enable=false
      - traefik.http.services.uptime.loadbalancer.server.port=3001
      - traefik.http.routers.uptime.rule=PathPrefix(`/m`)
      # - traefik.http.routers.uptime.tls=true
      # - traefik.http.routers.uptime.tls.certresolver=le
      # - traefik.http.middlewares.uptime.redirectscheme.scheme=https
      # - traefik.http.middlewares.uptime.redirectscheme.permanent=true
      # - traefik.http.middlewares.uptime.compress=true
    ports:
      - "9090:3001"
    volumes:
      - /volume1/docker/uptime/data:/app/data