version: "2.4"
services:
  redis:
    container_name: redis
    image: redis:6.0
    # networks: 
    #   public: {}
    restart: unless-stopped
    mem_limit: 50m
    mem_reservation: 25m
    cpus: 0.1

  postgres:
    container_name: postgres
    image: postgres:14
    # networks: 
    #   public: {}
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pg
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    mem_limit: 100m
    mem_reservation: 50m
    cpus: 0.2

volumes:
  pgdata:
  
# networks:
#   public:
#     external:
#       name: public