version: "2.4"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      WATCHTOWER_POLL_INTERVAL: 604800
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    container_name: redis
    image: redis:6.0
    networks:
      - utilites
    restart: unless-stopped
    mem_limit: 50m
    mem_reservation: 25m

  postgres:
    container_name: postgres
    image: postgres:14
    networks:
      - utilites
    restart: unless-stopped
    volumes:
      - utils_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    mem_limit: 256m
    mem_reservation: 50m

  git:
    image: gitea/gitea:1
    container_name: git
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=postgres
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=postgres
    restart: always
    networks:
      - utilites
    volumes:
      - /volume1/docker/gitea:/data
    ports:
      - "9200:3000"
      - "222:22"
    depends_on:
      - postgres

volumes:
  utils_pgdata:
    name: utils_pgdata
    external: true

networks:
  utilites:
    name: utilites
    external: true