version: "2.4"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      WATCHTOWER_POLL_INTERVAL: 604800
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    container_name: redis
    image: redis:6.0
    networks:
      - utilites
    restart: unless-stopped
    mem_limit: 50m
    mem_reservation: 25m

  postgres:
    container_name: postgres
    image: postgres:14
    networks:
      - utilites
    restart: unless-stopped
    volumes:
      - utils_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    mem_limit: 256m
    mem_reservation: 50m

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - ${DOCKER_DIR:-.}/wireguard/config:/config
    environment:
      PEERS: 2
      SERVERURL: ${SERVERURL:-}
      SERVERPORT: 51899
    ports:
      - "9203:5000"
      - "51899:51899/udp"
    restart: unless-stopped

  # WireGuard-UI service
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    # Use the network of the 'wireguard' service
    # This enables to show active clients in the status page
    network_mode: service:wireguard
    environment:
      - EMAIL_FROM_ADDRESS=dev@psmarcin.dev
      - EMAIL_FROM_NAME=psdev
      - SESSION_SECRET=${SESSION_SECRET:-}
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=password
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ${DOCKER_DIR:-.}/wireguard/db:/app/db
      - ${DOCKER_DIR:-.}/wireguard/config:/etc/wireguard

volumes:
  utils_pgdata:
    name: utils_pgdata
    external: true

networks:
  utilites:
    name: utilites
    external: true