version: "2.4"
services:
  redis:
    container_name: redis
    image: redis:6.0
    network: 
      bridge:
        ipv4_address:  172.17.0.100
    restart: unless-stopped
    mem_limit: 50m
    mem_reservation: 25m

  postgres:
    container_name: postgres
    image: postgres:14
    network: 
      bridge:
        ipv4_address:  172.17.0.101
    restart: unless-stopped
    volumes:
      - utils_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    mem_limit: 100m
    mem_reservation: 50m

volumes:
  utils_pgdata:
    external: true
  
# networks:
#   public:
#     external:
#       name: public