version: "2.4"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      WATCHTOWER_POLL_INTERVAL: 604800
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    container_name: redis
    image: redis:6.0
    networks:
      - utilites
    restart: unless-stopped
    mem_limit: 50m
    mem_reservation: 25m

  postgres:
    container_name: postgres
    image: postgres:14
    networks:
      - utilites
    restart: unless-stopped
    volumes:
      - utils_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    mem_limit: 256m
    mem_reservation: 50m

volumes:
  utils_pgdata:
    name: utils_pgdata
    external: true

networks:
  utilites:
    name: utilites
    external: true