TZ: Europe/Warsaw
ingress:
  main:
    enabled: true
    hosts:
      - host: up.local.dev
metrics:
  main:
    enabled: false
global:
  traefik:
    enableFixedMiddlewares: false
    fixedMiddlewares: []
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
persistence:
  config:
    enabled: true
    type: pvc
    storageClass: "nas-storage"
    mountPath: /app/data
    targetSelectAll: true
    subPath: "uptime/data"
    accessModes:
      - ReadWriteMany