TZ: Europe/Warsaw
ingress:
  main:
    enabled: true
    hosts:
      - host: jackett.local.dev
resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 50Mi
global:
  traefik:
    enableFixedMiddlewares: false
    fixedMiddlewares: []
persistence:
  config:
    enabled: true
    type: pvc
    storageClass: "nas-storage"
    mountPath: /config
    targetSelectAll: true
    subPath: "jackett/config"
    accessModes:
      - ReadWriteMany